# frozen_string_literal: true

source 'https://gems.ruby-china.com/'

gem 'colorize'
gem 'roo'
gem 'roo-xls'
gem 'ruby-units'

gem 'minitest', require: false
gem 'rdoc', require: false
gem 'rspec', require: false
gem 'rubocop', require: false
