# frozen_string_literal: true

# Copy from rrruby/Rakefile on 2020-07-30.

require 'fileutils'
require 'rake/testtask'
require 'rdoc/task'
require 'rspec/core/rake_task'
require 'rubocop/rake_task'

desc 'Install and update dependencies.'
task :setup do
  sh 'bundler install'
  sh 'bundler update --all'
end

RuboCop::RakeTask.new do |task|
  # task.options = %w[--except Style/AsciiComments --enable-pending-cops]
end

Rake::TestTask.new do |t|
  t.libs << 'test'
  t.libs << 'lib'
  t.test_files = FileList['test/**/test_*.rb', 'test/**/*_test.rb']
end

RSpec::Core::RakeTask.new

desc 'Run "src/main.rb" script'
task :run do
  ruby 'src/main.rb'
end

RDoc::Task.new do |rdoc|
  rdoc.rdoc_dir = 'build/html'
  rdoc.rdoc_files.include('src/**/*.rdoc', 'lib/**/*.rb')
end

desc 'Alias for rubocop'
task lint: :rubocop

desc 'Alias for rubocop:auto_correct'
task formatting: :'rubocop:auto_correct'

desc 'Task chain: lint, test & spec'
task check: %i[lint test spec]

desc 'Task chain: setup, lint, test, spec & rerdoc'
task build: %i[setup lint test spec rerdoc]

desc 'Default task, same as run'
task default: :run
