# frozen_string_literal: true

require 'fileutils'

# 安装依赖
task :install_dependencies do
  sh 'bundler install'
end

# 静态代码分析
task :lint do
  sh 'rubocop --except Style/AsciiComments'
end

# 单元测试
task :test do
  ruby 'test/run_test.rb'
end

# 运行
task :run do
  ruby 'src/main.rb'
end

# 清理文档
task :clean_documentation do
  FileUtils.remove_dir('doc/', force = true)
end

# 生成文档
task :generate_documentation do
  sh 'rdoc'
end

# 组合和默认任务
task setup: %i[install_dependencies]
task doc: %i[clean_documentation generate_documentation]
task default: %w[install_dependencies lint test doc]
