#!/usr/bin/env ruby -w
# frozen_string_literal: true

# zhengrr
# 2020-07-24 – 2020-07-27
# Unlicense

module RrExeNut3

  module Infoods

    ##
    # 国际食品数据系统网络（INFOODS）标签信息类
    #
    class TagInfo
      attr_reader :tag
      attr_reader :unit
      attr_reader :briefs

      def initialize(tag:, unit:, briefs:)
        @tag = tag
        @unit = unit
        @briefs = briefs
      end
    end

    ##
    # 国际食品数据系统网络（INFOODS）标签信息
    #
    TAGS = {
        AAA: TagInfo(
            tag: 'AAA',
            unit: 'mg',
            briefs: ['芳香族氨基酸', 'amino acids, total aromatic']),
        AAE8: TagInfo(
            tag: 'AAE8',
            unit: 'mg',
            briefs: ['八种必需氨基酸', 'amino acids, total essential']),
        aae10a: TagInfo(
            tag: 'AAE10A',
            unit: 'mg',
            names: ['必需氨基酸（十种，甲）', 'amino acids, total essential'],
            brief: 'includes the eight basic essential amino acids plus arginine and histidine',
            comment: 'Arginine and histidine are included in this definition of essential amino acids because they are essential for infants.'),
        aae10b: TagInfo(
            tag: 'AAE10B',
            unit: 'mg',
            names: ['必需氨基酸（十种，乙）', 'amino acids, total essential'],
            brief: 'includes the eight basic essential amino acids plus cystine and tyrosine',
            comment: 'Cystine and tyrosine are included in this definition of essential amino acids because of their sparing effects on the requirements for methionine and phenylalanine respectively.'),
        aae12: TagInfo(
            tag: 'AAE12',
            unit: 'mg',
            names: ['必需氨基酸（十二种）', 'amino acids, total essential'],
            brief: 'includes the eight basic essential amino acids plus arginine, histidine, cystine, and tyrosine',
            comment: 'Arginine and histidine are included in this definition of essential amino acids because they are essential for infants. Cystine and tyrosine are included because of their sparing effects on the requirements for methionine and phenylalanine respectively.'),
        aae_: TagInfo(
            tag: 'AAE-',
            unit: 'mg',
            names: ['必需氨基酸', 'amino acids, total essential'],
            brief: 'unknown or variable which amino acids are included in the total'),
        aas: TagInfo(
            tag: 'AAS',
            unit: 'mg',
            names: ['含硫氨基酸', 'amino acids, total sulphur-containing'],
            comment: 'The total value is the sum of cystine plus methionine.'),
        aat_: TagInfo(
            tag: 'AAT-',
            unit: 'mg',
            names: ['总氨基酸', 'amino acids, total'],
            brief: 'precise definition not specified',
            comment: 'When total amino acids are reported, they are usually the sum of whatever amino acids were analysed for that particular food. Consequently, this term is not precisely defined. Additional tagnames will be introduced when precise definitions exist.'),
        aceac: TagInfo(
            tag: 'ACEAC',
            unit: 'mg',
            names: ['醋酸', 'acetic acid']),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
        tag: TagInfo(
            tag: '',
            unit: '',
            names: [''],
            brief: '',
            comment: ''),
    }

  end

end
